# Generated by Django 5.1.7 on 2025-03-23 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetConnecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('etat', models.CharField(max_length=50)),
                ('attributs', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('sexe', models.CharField(blank=True, max_length=10, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('niveau_experience', models.CharField(default='débutant', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueUtilisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=100)),
                ('objet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_django_ConnectedGym.objetconnecte')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_django_ConnectedGym.utilisateur')),
            ],
        ),
    ]
