# Generated by Django 5.1.7 on 2025-04-29 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjetConnecte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("attribut", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("tapis", "Tapis de course"),
                            ("stepper", "Stepper"),
                            ("velo", "Vélo"),
                            ("rameur", "Rameur"),
                            ("elliptique", "Elliptique"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("neuf", "Neuf"),
                            ("tres_bon", "Très bon état"),
                            ("bon", "Bon état"),
                            ("moyen", "État moyen"),
                            ("mauvais", "Mauvais état"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "zone",
                    models.CharField(
                        choices=[
                            ("cardio", "Zone Cardio"),
                            ("ambiance", "Zone Ambiance"),
                        ],
                        max_length=50,
                    ),
                ),
                ("annee_achat", models.IntegerField(blank=True, null=True)),
                ("annee_fin", models.IntegerField(blank=True, null=True)),
                ("duree_max_jour", models.IntegerField(blank=True, null=True)),
                ("connectivite", models.CharField(max_length=100)),
                ("couleur", models.CharField(blank=True, max_length=50, null=True)),
                ("derniere_maintenance", models.DateField(blank=True, null=True)),
                ("image", models.URLField(blank=True, max_length=300, null=True)),
                (
                    "inclinaison_max",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("marque", models.CharField(max_length=100)),
                ("puissance", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("panne", "Panne"),
                            ("maintenance", "Maintenance"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "vitesse_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("intensite", models.CharField(blank=True, max_length=50, null=True)),
                ("heure_debut_utilisation", models.TimeField(blank=True, null=True)),
                ("heure_fin_utilisation", models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="HistoriqueUtilisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("action", models.CharField(max_length=100)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "objet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="App_django_ConnectedGym.objetconnecte",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfilUtilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sexe", models.CharField(blank=True, max_length=10, null=True)),
                ("date_naissance", models.DateField(blank=True, null=True)),
                (
                    "niveau_experience",
                    models.CharField(default="débutant", max_length=50),
                ),
                (
                    "photo_profil",
                    models.ImageField(
                        blank=True, null=True, upload_to="photos_profil/"
                    ),
                ),
                ("points", models.IntegerField(default=1)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
