# Generated by Django 5.1.7 on 2025-04-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_django_ConnectedGym", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historiqueutilisation",
            name="calories_brulees",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="historiqueutilisation",
            name="distance_parcourue",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="historiqueutilisation",
            name="duree_utilisation",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historiqueutilisation",
            name="inclinaison_moyenne",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historiqueutilisation",
            name="intensite_moyenne",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historiqueutilisation",
            name="puissance_moyenne",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historiqueutilisation",
            name="vitesse_moyenne",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
