# Generated by Django 5.1.7 on 2025-04-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_django_ConnectedGym', '0002_alter_historiqueutilisation_utilisateur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='photos_profil/'),
        ),
    ]
