# Generated by Django 5.1.7 on 2025-04-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "App_django_ConnectedGym",
            "0002_historiqueutilisation_calories_brulees_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="objetconnecte",
            name="intensite_max",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="objetconnecte",
            name="puissance_max",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="objetconnecte",
            name="type_resistance",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="objetconnecte",
            name="type_transmission",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="objetconnecte",
            name="statut",
            field=models.CharField(
                choices=[
                    ("actif", "Actif"),
                    ("inactif", "Inactif"),
                    ("maintenance", "En maintenance"),
                ],
                default="actif",
                max_length=20,
            ),
        ),
    ]
