# Generated by Django 5.1.7 on 2025-04-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_django_ConnectedGym', '0003_profilutilisateur_photo_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='points',
            field=models.IntegerField(default=1),
        ),
    ]
