# Generated by Django 5.1.7 on 2025-04-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_django_ConnectedGym", "0003_objetconnecte_intensite_max_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="objetconnecte",
            name="amorti",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="objetconnecte",
            name="ventilation_frontale",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="objetconnecte",
            name="intensite",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="objetconnecte",
            name="puissance_max",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
