# Generated by Django 5.1.7 on 2025-04-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_django_ConnectedGym", "0004_profilutilisateur_points"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="objetconnecte",
            name="attributs",
        ),
        migrations.AddField(
            model_name="objetconnecte",
            name="annee_achat",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="objetconnecte",
            name="annee_fin",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="objetconnecte",
            name="attribut",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="objetconnecte",
            name="capacite_max",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="objetconnecte",
            name="commande_vocale",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="objetconnecte",
            name="connectivite",
            field=models.CharField(default="Bluetooth", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="objetconnecte",
            name="couleur",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="objetconnecte",
            name="derniere_maintenance",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="objetconnecte",
            name="duree_max_jour",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="objetconnecte",
            name="est_disponible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="objetconnecte",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="objets/"),
        ),
        migrations.AddField(
            model_name="objetconnecte",
            name="inclinaison_max",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="objetconnecte",
            name="intensite",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="objetconnecte",
            name="marque",
            field=models.CharField(default="Samsung", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="objetconnecte",
            name="precision",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="objetconnecte",
            name="puissance",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="objetconnecte",
            name="statut",
            field=models.CharField(
                choices=[
                    ("actif", "Actif"),
                    ("panne", "Panne"),
                    ("maintenance", "Maintenance"),
                ],
                default="actif",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="objetconnecte",
            name="vitesse",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="objetconnecte",
            name="vitesse_max",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="objetconnecte",
            name="volume_max",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="objetconnecte",
            name="zone",
            field=models.CharField(
                choices=[
                    ("cardio", "Zone Cardio"),
                    ("detente", "Zone Détente"),
                    ("ambiance", "Zone Ambiance"),
                ],
                default="cardio",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="objetconnecte",
            name="etat",
            field=models.CharField(
                choices=[
                    ("neuf", "Neuf"),
                    ("tres_bon", "Très bon état"),
                    ("bon", "Bon état"),
                    ("moyen", "État moyen"),
                    ("mauvais", "Mauvais état"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="objetconnecte",
            name="type",
            field=models.CharField(
                choices=[
                    ("tapis", "Tapis de course"),
                    ("balance", "Balance"),
                    ("ventilateur", "Ventilateur"),
                    ("led", "LED"),
                    ("enceinte", "Enceinte"),
                ],
                max_length=50,
            ),
        ),
    ]
