# Generated by Django 5.1.7 on 2025-05-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_django_ConnectedGym", "0005_objetconnecte_hauteur_marche_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="objetconnecte",
            name="est_disponible",
            field=models.BooleanField(default=True),
        ),
    ]
