# Generated by Django 5.1.7 on 2025-04-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_django_ConnectedGym", "0005_remove_objetconnecte_attributs_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="objetconnecte",
            name="capacite_max",
        ),
        migrations.RemoveField(
            model_name="objetconnecte",
            name="commande_vocale",
        ),
        migrations.RemoveField(
            model_name="objetconnecte",
            name="est_disponible",
        ),
        migrations.RemoveField(
            model_name="objetconnecte",
            name="precision",
        ),
        migrations.RemoveField(
            model_name="objetconnecte",
            name="vitesse",
        ),
        migrations.RemoveField(
            model_name="objetconnecte",
            name="volume_max",
        ),
        migrations.AddField(
            model_name="objetconnecte",
            name="heure_debut_utilisation",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="objetconnecte",
            name="heure_fin_utilisation",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="objetconnecte",
            name="couleur",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="objetconnecte",
            name="image",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="objetconnecte",
            name="inclinaison_max",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="objetconnecte",
            name="intensite",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="objetconnecte",
            name="puissance",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="objetconnecte",
            name="type",
            field=models.CharField(
                choices=[
                    ("tapis", "Tapis de course"),
                    ("stepper", "Stepper"),
                    ("velo", "Vélo"),
                    ("rameur", "Rameur"),
                    ("elliptique", "Elliptique"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="objetconnecte",
            name="zone",
            field=models.CharField(
                choices=[("cardio", "Zone Cardio"), ("ambiance", "Zone Ambiance")],
                max_length=50,
            ),
        ),
    ]
