# Generated by Django 5.1.7 on 2025-05-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_django_ConnectedGym", "0006_objetconnecte_est_disponible"),
    ]

    operations = [
        migrations.AddField(
            model_name="historiqueutilisation",
            name="inclinaison_max",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="historiqueutilisation",
            name="intensite",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historiqueutilisation",
            name="puissance",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="historiqueutilisation",
            name="vitesse_max",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
