# Generated by Django 5.1.7 on 2025-05-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "App_django_ConnectedGym",
            "0007_historiqueutilisation_inclinaison_max_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historiqueutilisation",
            name="calories_brulees",
        ),
        migrations.RemoveField(
            model_name="historiqueutilisation",
            name="distance_parcourue",
        ),
        migrations.RemoveField(
            model_name="historiqueutilisation",
            name="duree_utilisation",
        ),
        migrations.RemoveField(
            model_name="historiqueutilisation",
            name="inclinaison_moyenne",
        ),
        migrations.RemoveField(
            model_name="historiqueutilisation",
            name="intensite_moyenne",
        ),
        migrations.RemoveField(
            model_name="historiqueutilisation",
            name="puissance_moyenne",
        ),
        migrations.RemoveField(
            model_name="historiqueutilisation",
            name="vitesse_moyenne",
        ),
        migrations.AddField(
            model_name="historiqueutilisation",
            name="amorti",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historiqueutilisation",
            name="hauteur_marche",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="historiqueutilisation",
            name="longueur_pas",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="historiqueutilisation",
            name="longueur_rail",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="historiqueutilisation",
            name="type_mouvement",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historiqueutilisation",
            name="type_resistance",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historiqueutilisation",
            name="type_transmission",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historiqueutilisation",
            name="ventilation_frontale",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
