# Generated by Django 5.1.7 on 2025-05-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "App_django_ConnectedGym",
            "0008_remove_historiqueutilisation_calories_brulees_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historiqueutilisation",
            name="etat",
            field=models.CharField(
                choices=[
                    ("neuf", "Neuf"),
                    ("tres_bon", "Très bon état"),
                    ("bon", "Bon état"),
                    ("moyen", "État moyen"),
                    ("mauvais", "Mauvais état"),
                ],
                default="moyen",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
