# Generated by Django 5.1.7 on 2025-05-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_django_ConnectedGym", "0009_historiqueutilisation_etat"),
    ]

    operations = [
        migrations.AddField(
            model_name="historiqueutilisation",
            name="image",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
