# Generated by Django 5.2 on 2025-05-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_django_ConnectedGym', '0010_historiqueutilisation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetconnecte',
            name='calories_brulees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
