# Generated by Django 5.1.7 on 2025-05-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_django_ConnectedGym", "0011_objetselectionne"),
    ]

    operations = [
        migrations.AddField(
            model_name="objetselectionne",
            name="climatisation",
            field=models.CharField(
                blank=True,
                choices=[("on", "ON"), ("off", "OFF")],
                max_length=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="objetselectionne",
            name="lumiere",
            field=models.CharField(
                blank=True,
                choices=[
                    ("basse", "Basse"),
                    ("moyenne", "Moyenne"),
                    ("forte", "Forte"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="objetselectionne",
            name="musique",
            field=models.CharField(
                blank=True,
                choices=[
                    ("aucune", "Aucune"),
                    ("zen", "Zen"),
                    ("cardio", "Cardio"),
                    ("motivation", "Motivation"),
                    ("muscu", "Musculation"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="objetselectionne",
            name="temperature",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
