# Generated by Django 5.2 on 2025-05-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_django_ConnectedGym', '0011_objetconnecte_calories_brulees'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetconnecte',
            name='duree_utilisation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
