# Generated by Django 5.2 on 2025-05-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_django_ConnectedGym', '0012_objetconnecte_duree_utilisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiqueutilisation',
            name='distance_parcourue',
            field=models.FloatField(blank=True, help_text="Distance parcourue pendant l'utilisation (en km)", null=True),
        ),
        migrations.AddField(
            model_name='objetconnecte',
            name='distance_parcourue',
            field=models.FloatField(blank=True, help_text="Distance parcourue pendant l'utilisation (en km)", null=True),
        ),
    ]
