# Generated by Django 5.1.7 on 2025-05-02 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App_django_ConnectedGym", "0012_objetselectionne_climatisation_and_more"),
        (
            "App_django_ConnectedGym",
            "0013_historiqueutilisation_distance_parcourue_and_more",
        ),
    ]

    operations = []
