# Generated by Django 5.1.7 on 2025-05-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_django_ConnectedGym", "0014_merge_20250502_1509"),
    ]

    operations = [
        migrations.AddField(
            model_name="objetselectionne",
            name="ambiance",
            field=models.CharField(
                blank=True,
                choices=[
                    ("aucune", "Aucune"),
                    ("zen", "Zen"),
                    ("cardio", "Cardio"),
                    ("motivation", "Motivation"),
                    ("muscu", "Musculation"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="objetselectionne",
            name="musique",
            field=models.CharField(
                blank=True,
                choices=[
                    ("aucune", "Aucune"),
                    ("rap", "Rap"),
                    ("classique", "Classique"),
                    ("jazz", "Jazz"),
                    ("pop", "Pop"),
                    ("rock", "Rock"),
                    ("electro", "Electro"),
                    ("reggae", "Reggae"),
                    ("country", "Country"),
                    ("hiphop", "Hip-hop"),
                    ("rnb", "R&B"),
                    ("latino", "Latino"),
                    ("kpop", "K-Pop"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
