# Generated by Django 5.1.7 on 2025-05-02 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_django_ConnectedGym", "0015_objetselectionne_ambiance_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoriqueAmbiance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "ambiance",
                    models.CharField(
                        choices=[
                            ("aucune", "Aucune"),
                            ("zen", "Zen"),
                            ("cardio", "Cardio"),
                            ("motivation", "Motivation"),
                            ("muscu", "Musculation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "musique",
                    models.CharField(
                        choices=[
                            ("aucune", "Aucune"),
                            ("rap", "Rap"),
                            ("classique", "Classique"),
                            ("jazz", "Jazz"),
                            ("pop", "Pop"),
                            ("rock", "Rock"),
                            ("electro", "Electro"),
                            ("reggae", "Reggae"),
                            ("country", "Country"),
                            ("hiphop", "Hip-hop"),
                            ("rnb", "R&B"),
                            ("latino", "Latino"),
                            ("kpop", "K-Pop"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "lumiere",
                    models.CharField(
                        choices=[
                            ("basse", "Basse"),
                            ("moyenne", "Moyenne"),
                            ("forte", "Forte"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "climatisation",
                    models.CharField(
                        choices=[("on", "ON"), ("off", "OFF")], max_length=5
                    ),
                ),
                ("temperature", models.IntegerField(blank=True, null=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
