# Generated by Django 5.1.7 on 2025-05-02 20:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_django_ConnectedGym", "0016_historiqueambiance"),
    ]

    operations = [
        migrations.AddField(
            model_name="objetselectionne",
            name="date_debut",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="objetselectionne",
            name="duree_heures",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
