# Generated by Django 5.1.7 on 2025-05-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_django_ConnectedGym", "0017_objetselectionne_date_debut_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objetconnecte",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="connectedgym-images/"
            ),
        ),
    ]
