# Generated by Django 5.2 on 2025-05-03 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_django_ConnectedGym', '0018_demandesuppressionobjet'),
        ('App_django_ConnectedGym', '0019_alter_objetconnecte_image'),
    ]

    operations = [
    ]
