# Generated by Django 5.2 on 2025-05-03 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_django_ConnectedGym', '0020_merge_20250504_0016'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilutilisateur',
            name='niveau_experience',
            field=models.CharField(choices=[('débutant', 'Débutant'), ('intermédiaire', 'Intermédiaire'), ('avancé', 'Avancé'), ('expert', 'Expert')], default='débutant', max_length=20),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='profils/'),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='sexe',
            field=models.CharField(blank=True, default='Homme', max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HistoriquePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_action', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
